### PR TITLE
Benny/statusapp68 enable touch

### PR DESCRIPTION
**Pull request by Bennyoak**
Ugh - Rebasing the branch derped the PR in #86 
Here's all the things rebased and updated.

### CODE REVIEW

**Comment by Bennyoak** [comment]
Hang on for this. I have to change something.

**Comment by daviddahl** [comment]
no worries. I think tomorrow will be "merge bennys patches day"

**Comment by Bennyoak** [comment]
Ok - This one is up to date with the current b-3 and patched.

**Comment by daviddahl** [comment]
closing as outdated

**Pull request closed without merging**
