### PR TITLE
First set of new icons

### PR DESCRIPTION
**Pull request by helveticade**
Here's an initial set of icons in SVG format as per #73.
They still need to be referenced in CSS and I am yet to do this.

For reference:
screen shot 2015-08-04 at 15 17 46

### CODE REVIEW

**Comment by daviddahl** [comment]
I should merge this as I am on a plane all afternoon tomorrow

**Comment by daviddahl** [comment]
If you like I can merge this and add them to the app, unless you have all the rest of the icons., etc

**Comment by helveticade** [comment]
Merge now, I'll make a PR with more as I draw them.

**Comment by daviddahl** [comment]
I think "sync" is missing from the svg items in this PR

**Comment by daviddahl** [comment]
nevermind, it is in "shape.svg"

**Pull request merged**
