### PR TITLE
Set test to prevent splash on android

### PR DESCRIPTION
**Pull request by Bennyoak**
This addresses issue #78 
Needs testing on Android device

### CODE REVIEW

**Comment by daviddahl** [comment]
Did you find this snippet somewhere? I thought the thing to do was to just remove the "splash config" bits from config.xml:
﻿﻿https://github.com/Crypton/statusapp/blob/b-3/mobileapp/config.xml#L25-L34
And move these into an iOS only bit:
https://github.com/Crypton/statusapp/blob/b-3/mobileapp/config.xml#L19-L20

**Comment by Bennyoak** [comment]
Ah - must have misunderstood. I can fix that.

**Comment by daviddahl** [comment]
Also, for future reference, I have tried to abstract the platform discovery here: https://github.com/Crypton/statusapp/blob/b-3/mobileapp/www/js/index.js#L1425-L1447

**Comment by daviddahl** [comment]
I have already fixed this in b-3: https://github.com/Crypton/statusapp/commit/62b457cbe3d9bfadefe5715b6f9ffe88c7210902#diff-3940aa769bdbd4def6d363c085bc31c0L26

**Pull request closed without merging**
